In [1]:
import pandas as pd

shopping_data = pd.read_csv("data/raw/shopping.csv")
print(shopping_data.columns.tolist())

['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Shipping Type', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

In [ ]:
shopping_data.head()
# check the unique values if u know the key!
shopping_data['Season'].unique()

In [ ]:
shopping_data.pivot_table(values='Purchase Amount (USD)', index='Gender',columns='Season', aggfunc= 'sum').reset_index().sort_values('Summer', ascending=False)

In [2]:
# label code block section 
print("*"*9)
print("Questions")
print("*"*9)

# output the questions to be answered here
print("Q1) Which season yields the highest amount of purchases overall?\n"
      "Q3) What is the relationship between the customer ages and their frequency of purchases?\n"
      "Q5) Of the most popular sizes purchased overall, which has yields the highest reviews?\n"
      "Q6) How frequently is a promo code used by the customers with the highest frequency of purchases?")

*********
Questions
*********
Q1) Which season yields the highest amount of purchases overall?
Q3) What is the relationship between the customer ages and their frequency of purchases?
Q5) Of the most popular sizes purchased overall, which has yields the highest reviews?
Q6) How frequently is a promo code used by the customers with the highest frequency of purchases?

In [3]:
print("*"* 76)
print("Q1) Investigating seaonality of purchase frequency by season with .groupby()")
print("*"* 76)

round(shopping_data.groupby('Season')['Purchase Amount (USD)'].sum().sort_values(ascending=False), 2)

****************************************************************************
Q1) Investigating seaonality of purchase frequency by season with .groupby()
****************************************************************************

Season
Winter    50681.68
Fall      41004.57
Summer    36446.81
Spring    22829.42
Name: Purchase Amount (USD), dtype: float64

In [ ]:
print("*"* 12)
print("Q1) Findings")
print("*"* 12)
season_sum = round(shopping_data.groupby('Season')['Purchase Amount (USD)'].sum(),2)

season_max = season_sum.idxmax() # assignment of highest season based on highest USD total
season_min = season_sum.idxmin() # assignment of lowest season based on highest USD total

amount_max = season_sum.max()  # total USD of highest season 
amount_min = season_sum.min()   # total USD of lowest season 
diff_usd = round(amount_max - amount_min, 2)

print(
    f"Q1) The most profitable season is {season_max}, yielding ${amount_max}."
    f"\n This amount is ${diff_usd} more than the lowest purchase amount of ${amount_min} during the lowest yield season of {season_min}.")

************
Q1) Findings
************
Q1) The most profitable season is Winter, yielding $50681.68.
 This amount is $27852.26 more than the lowest purchase amount of $22829.42 during the lowest yield season, Spring.

In [7]:
print("*"*80)
print("Q3) Investigating seasonality of frequency and age with .dropna() and .groupby()") 
print("*"*80)

age_freq = round(shopping_data.dropna(subset=['Frequency of Purchases']).groupby('Frequency of Purchases')['Age'].mean(),1)
age_freq

********************************************************************************
Q3) Investigating seasonality of frequency and age with .dropna() and .groupby()
********************************************************************************

Frequency of Purchases
Annually     34.1
Bi-Weekly    34.6
Monthly      34.2
Quarterly    33.7
Weekly       35.0
Name: Age, dtype: float64

In [13]:
print("*"* 12)
print("Q3) Findings")
print("*"* 12)

age_min = age_freq.min()
age_max = age_freq.max() 
diff_age = round(age_max - age_min, 2) 

# add the commas to the list of column names
freq_cols = ', '.join(age_freq.index.tolist())
print(
    f" Q3) There is not a relationship with frequency of purchases and age across the frequency columns: {freq_cols}."
    f"\n The average age ranges from {age_max} and {age_min}, with a difference of {diff_age} year(s).")

************
Q3) Findings
************
 Q3) There is not a relationship with frequency of purchases and age across the frequency columns: Annually, Bi-Weekly, Monthly, Quarterly, Weekly.
 The average age ranges from 35.0 and 33.7, with a difference of 1.3 year(s).

In [164]:
print("*"*80)
print("Q5) Investigating seasonality of item size and review rating with .pivot_table()") 
print("*"*80)# "Q5) Of the most popular sizes purchased overall, which  yields the highest reviews?\n"

size_cols = round(shopping_data.dropna(subset=['Review Rating']).pivot_table(values='Review Rating', index='Size', aggfunc= 'mean').sort_values('Review Rating', ascending=False), 2)
size_cols

********************************************************************************
Q5) Investigating seasonality of item size and review rating with .pivot_table()
********************************************************************************

      Review Rating
Size
M              3.96
S              3.90
L              3.86
XL             3.80

In [160]:
print("*"* 12)
print("Q5) Findings")
print("*"* 12)

size_max = ''.join(size_cols.idxmax().tolist()) #  size with highest average review rating 
size_min = ''.join(size_cols.idxmin().tolist()) #  size with lowest amount of review rating

reviews_max = round(size_cols.max().values[0], 2) # highest average review rating across all sizes
reviews_min = round(size_cols.min().values[0], 2) # lowesr average review rating across all sizes

print(f'The most popular size is {size_max} with an average review rating of {reviews_max}. Oppositely, the least popular size {size_min} has an average review rating of {reviews_min}.')

************
Q5) Findings
************
The most popular size is M with an average review rating of 3.96. Oppositely, the least popular size XL has an average review rating of 3.8.

In [ ]:
print("*"* 76)
print("Q6) Investigating seaonality of promo code usage by purchase frequency with .groupby()")
print("*"* 76)

print(shopping_data['Frequency of Purchases'].unique())
print(shopping_data['Promo Code Used'].unique())

shopping_data['Frequency of Purchases'].value_counts() # "Weekly" is most often, "Quarterly" is most popular

****************************************************************************
Q6) Investigating seaonality of promo code usage by purchase frequency with .groupby()
****************************************************************************
<StringArray>
[nan, 'Monthly', 'Bi-Weekly', 'Quarterly', 'Weekly', 'Annually']
Length: 6, dtype: str
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Frequency of Purchases
Quarterly    664
Monthly      405
Annually     307
Bi-Weekly    155
Weekly        29
Name: count, dtype: int64

In [ ]:
weekly_customers = shopping_data[shopping_data['Frequency of Purchases'] == 'Weekly'] #each index checks if True (weekly) is true when wrapped in shopping_data dataframe

quart_customers = shopping_data[shopping_data['Frequency of Purchases'] == 'Quarterly']

,Customer ID,Age,Gender,Item Purchased,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Shipping Type,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
12,3341,27.0,Female,Handbag,29.430620,Virginia,XL,Black,Summer,NaN,Standard,No,2,Credit Card,Weekly
61,3544,28.0,Female,T-shirt,20.777548,Colorado,M,Ruby Red,Spring,NaN,Standard,No,2,Credit Card,Weekly
100,3667,44.0,Female,Socks,21.280078,Alabama,M,Burnt orange,Winter,NaN,Standard,No,2,Credit Card,Weekly
101,3076,37.0,Female,Sweater,23.671008,Utah,XL,Muted mustard yellow,Fall,4.0,Standard,No,5,Credit Card,Weekly
212,3058,51.0,Female,Boots,32.979809,North Carolina,M,Black,Winter,4.0,Standard,No,12,Credit Card,Weekly
287,2138,NaN,Female,Boots,31.150173,Indiana,XL,Terra cotta,Winter,NaN,Standard,No,2,Credit Card,Weekly
732,3274,22.0,Female,Gloves,33.925890,NaN,S,Aubergine,Fall,NaN,Standard,No,17,Credit Card,Weekly
762,2928,29.0,Male,Boots,29.571201,Missouri,M,Burnt orange,Winter,NaN,Standard,No,1,Credit Card,Weekly
770,3537,23.0,Female,T-shirt,34.934733,Minnesota,L,Lavender,Summer,NaN,Standard,No,4,Credit Card,Weekly
805,2379,19.0,Male,Leggings,38.263111,New Hampshire,L,Muted mustard yellow,Fall,4.0,Next Day Air,No,17,Debit Card,Weekly
809,1753,48.0,Male,Hoodie,32.072613,South Dakota,L,Black,Winter,4.0,Standard,No,10,Debit Card,Weekly
921,3293,23.0,Male,Jacket,24.598731,NaN,L,Ruby Red,Winter,5.0,Standard,No,2,Debit Card,Weekly
938,3841,31.0,Non-binary,Pajamas,28.379849,Idaho,M,Muted mustard yellow,Winter,4.0,Standard,No,4,Debit Card,Weekly
943,3379,NaN,Male,Running Shoes,30.027694,Minnesota,L,Fuchsia,Spring,NaN,Standard,No,3,Debit Card,Weekly
981,3382,NaN,Male,Jacket,32.255018,Minnesota,L,Black,Fall,5.0,Standard,No,14,Debit Card,Weekly
984,3621,30.0,Female,Sweater,19.584938,Louisiana,M,Mauve,Fall,2.0,Standard,No,5,Debit Card,Weekly
1004,2875,41.0,Male,Pajamas,32.562647,Colorado,L,Muted mustard yellow,Winter,NaN,Standard,No,10,Debit Card,Weekly
1091,3137,46.0,Female,Handbag,23.120640,Minnesota,M,Fuchsia,Summer,NaN,Express,No,10,Debit Card,Weekly
1217,3605,58.0,Non-binary,Running Shoes,29.067419,Louisiana,M,Fuchsia,Summer,4.0,Standard,No,12,Debit Card,Weekly
1237,3381,19.0,Female,Socks,34.397429,North Dakota,L,Ruby Red,Winter,4.0,Standard,No,4,Debit Card,Weekly
1275,3502,41.0,Male,Socks,40.755544,Nebraska,M,Terra cotta,Fall,NaN,Standard,No,1,Debit Card,Weekly
1295,2893,55.0,Male,Running Shoes,33.780026,NaN,M,Turquoise,Summer,5.0,Standard,No,8,Debit Card,Weekly
1371,2556,31.0,Male,Shorts,30.193764,NaN,M,Pale peach,Summer,NaN,Standard,No,11,Debit Card,Weekly
1409,2642,NaN,Male,Dress,39.568185,Vermont,XL,Pale peach,Spring,NaN,Standard,No,11,Debit Card,Weekly
1718,3208,36.0,Male,Pajamas,33.971687,Arizona,XL,Muted mustard yellow,Winter,NaN,Standard,No,18,PayPal,Weekly
1738,3266,40.0,Female,Sunglasses,31.930732,Alabama,M,Baby blue,Spring,NaN,Standard,No,5,PayPal,Weekly
1752,1922,40.0,Female,Gloves,25.909441,Michigan,M,Black,Winter,4.0,Standard,No,1,PayPal,Weekly
1766,3674,27.0,Male,Jacket,29.805063,Rhode Island,M,Black,Fall,2.0,Next Day Air,No,16,PayPal,Weekly
1825,3089,30.0,Female,T-shirt,33.834596,NaN,M,Fuchsia,Summer,4.0,Standard,No,20,PayPal,Weekly